Revert "comment out normal rm to check sudo rm"
This reverts commit df06d188cf80c4b9167628400624d1f8f0f9c5c7.

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -7,11 +7,11 @@ echo "Killing ssh-agent with PID ${SSH_AGENT_PID}"
 eval "$(ssh-agent -k)"
 
 echo "Removing secrets directory: ${SECRETS_DIR}"
-# rm -rf "${SECRETS_DIR}" || {
-#   echo "Tried running: rm -rf ${SECRETS_DIR}"
-#   echo "But it failed leaving the following files as residue"
-#   ls -la "${SECRETS_DIR}"
-# }
+rm -rf "${SECRETS_DIR}" || {
+  echo "Tried running: rm -rf ${SECRETS_DIR}"
+  echo "But it failed leaving the following files as residue"
+  ls -la "${SECRETS_DIR}"
+}
 
 if [ -d "${SECRETS_DIR}" ]; then
   echo "Attempting to remove with sudo"
